/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./ui/templates/**/*.html",
    "./ui/static/ui/js/**/*.js",
  ],
  theme: {
    extend: {
      colors: {
        "bg-base": "#FAF9F6",
        "bg-surface": "#FFFFFF",
        "bg-surface-alt": "#F3F1ED",
        "bg-inset": "#EBE8E2",
        "border-default": "#E0DCD4",
        "border-strong": "#C8C3BA",
        "text-primary": "#1C1917",
        "text-secondary": "#57534E",
        "text-muted": "#A8A29E",
        "text-inverse": "#FAF9F6",
        accent: "#2D7D7B",
        "accent-hover": "#246563",
        "accent-active": "#1B4E4D",
        "accent-subtle": "#D4EDEB",
        "accent-light": "#EBF7F6",
        success: "#4A7C59",
        "success-subtle": "#E4F0E8",
        warning: "#B8860B",
        "warning-dark": "#8B6914",
        "warning-subtle": "#FDF3DC",
        error: "#B91C1C",
        "error-hover": "#991B1B",
        "error-subtle": "#FDE8E8",
      },
      fontFamily: {
        sans: [
          '"Inter"',
          '"Noto Sans JP"',
          "-apple-system",
          "BlinkMacSystemFont",
          '"Segoe UI"',
          "sans-serif",
        ],
        mono: ['"JetBrains Mono"', '"Noto Sans JP"', "monospace"],
      },
      borderRadius: {
        sm: "6px",
        md: "10px",
        lg: "16px",
        full: "9999px",
      },
      boxShadow: {
        sm: "0 1px 3px rgba(0,0,0,0.08), 0 1px 2px rgba(0,0,0,0.06)",
        md: "0 4px 6px rgba(0,0,0,0.07), 0 2px 4px rgba(0,0,0,0.06)",
        lg: "0 10px 15px rgba(0,0,0,0.07), 0 4px 6px rgba(0,0,0,0.05)",
        xl: "0 20px 25px rgba(0,0,0,0.08), 0 10px 10px rgba(0,0,0,0.04)",
      },
      spacing: {
        1: "4px",
        2: "8px",
        3: "12px",
        4: "16px",
        5: "20px",
        6: "24px",
        8: "32px",
        10: "40px",
        12: "48px",
        16: "64px",
      },
    },
  },
  plugins: [],
};
